AC2017関連追加
KCCTdensan/KCCTdensan.github.io.old pull request #3
Opened 2017-12-04 06:21 UTC by Yuelia35

AC2017記事(電算部公式ページにあるもののみ)のまとめページと三日目の記事(担当:Yuelia35)を追加
一日も遅れてしまい申し訳ございませんでした

2017-12-04 07:11 UTC, TateIsuKanna requested changes
HTMLについて色々

2017-12-04 07:11 UTC, TateIsuKanna commented on AC2017/dec3.html
> +    ���|�[�g�Ȃǂ���Ƃ�,��Ǔ_��,��Ƣ.��ɂ��Ȃ����ƌ���ꂽ���Ƃ����邩����܂���.�ł���,IME�͏���ݒ�ł͓�{���͎��ɋ�Ǔ_��A��Ƣ�B��őł悤�ɂȂ�Ă��镨�������ł�.�ꉞ�ϊ���,.�ɂł��܂���������,�Ƃ������Ƃ�<b>��Ǔ_��͂Ɋւ���ݒ��ύX����Γ�{���͂ł�ꔭ��,
強調を示したい時は`<b>`では無く`<em>`や`<strong>`(より強い)を使うと良いです．`<b>`は太字にするという見た目の意味しか持ちません．
https://developer.mozilla.org/ja/docs/Web/HTML/Element/b#Usage_notes

2017-12-04 07:11 UTC, TateIsuKanna commented on AC2017/dec3.html
> +    ���̋L����<a href="https://adventar.org/calendars/2485">KCCT-Densan Advent Calendar 2017</a>��3��ڂ̋L���ł�.<br /><br /><br />
[\<br\> を、行間を拡げるために使用してはなりません。](https://developer.mozilla.org/ja/docs/Web/HTML/Element/br#Notes)
上の文を`<p>`で囲むのがいいと思います．
あとスラッシュ無しの`<br>`で大丈夫ですよ．(好みだったらごめん)

2017-12-04 07:11 UTC, TateIsuKanna commented on AC2017/dec3.html
> +    ���ɂ�IME�ɂ͗l�X�Ȑݒ肪����܂���,���Ԃƕ������Ɠǂ݂₷��<font size="1">�Ǝ��̕��͗͂Ƃ��Ɩʓ|</font>�Ȃǂ̓s���ɂ�肱�Ƃɂ��ďȗ��Ƃ����Ă��������܂�.
`<font>`は[廃止された](https://developer.mozilla.org/ja/docs/Web/HTML/Element/font)タグです．
`<span style="font-size: 50%;">小さくしたい!</span>`
等とするのがいいと思います．

2017-12-04 07:11 UTC, TateIsuKanna commented on AC2017/dec3.html
> +    <h3>�ϊ�����ϊ��L�[�ɂ���͐ؑ�</h3>
段落として囲める部分は`<br>`を使わず`<p>`で囲むのがいいです．

2017-12-04 07:11 UTC, TateIsuKanna commented on AdventC.html
> +            KCCT-Densan Advent Calendar�̋L���ŁA���y�[�W�ɂ���L���̈ꗗ�ł�<br />
ここの`<br>`は不要です．(そもそもこの行1つ上に書いたほうが適切?)

2017-12-04 07:11 UTC, TateIsuKanna commented on AC2017/dec3.html
> +<!DOCTYPE html>
ファイルの文字エンコーディングをUTF-8にして下さい．
`<meta charset="UTF-8">`もお忘れなく．

2017-12-04 12:06 UTC, Yuelia35 commented
@TateIsuKanna 
修正しました

2017-12-04 12:49 UTC, TateIsuKanna commented
ところどころ`<br>`にし忘れ?わざと?

2017-12-04 13:49 UTC, Yuelia35 commented
@TateIsuKanna 
Visualstudioで打つと<br>が自動的にスラッシュ入りました
<br>となっているのはあとからVimで打った分です
<br>に統一すべきでしょうか

2017-12-04 13:57 UTC, TateIsuKanna commented
そこはお好みで．どちらかに統一するのをおすすめするけどね
そのVSの挙動はオプションで変えられます．
https://msdn.microsoft.com/ja-jp/library/ms178724.aspx

2017-12-04 14:35 UTC, Yuelia35 commented
PullRequestは再度する必要はありますか

2017-12-04 14:36 UTC, TateIsuKanna commented
pushしてもらえれば大丈夫です．

2017-12-04 14:49 UTC, Yuelia35 commented
ではこれでお願いします

2017-12-04 14:50 UTC, TateIsuKanna approved these changes

2017-12-04 14:52 UTC, merged

2017-12-09 15:25 UTC, TateIsuKanna commented
`name`のままになってたので f4df63d で`charset`に修正しておきました．